---
title: "Playground"
output: volker::html_report
vignette: >
  %\VignetteIndexEntry{Playground}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r include=FALSE}
knitr::opts_chunk$set(
  echo = F,
  knitr.table.format = "html"
)
```


```{r include=FALSE}
library(tidyverse)
library(volker)
```


```{r include=FALSE}
# Checking all plots 

theme_set(theme_vlkr(base_fill = c("grey"))) 

tab_counts_one(ds, sd_gender)
# Counts 
plot_counts_one(ds, sd_gender, numbers = T) 
plot_counts_items(ds, starts_with("cg_adoption_"), numbers = T)
plot_counts_one_grouped(ds, adopter, sd_gender)
plot_counts_items_grouped(ds, ...) # not implemented 

# Metrics
plot_metrics_one(ds, sd_age, numbers =T) # add mean? 
plot_metrics_one_grouped(ds, sd_age, sd_gender, bars = "box")
plot_metrics_items(ds, starts_with("cg_adoption"))
plot_metrics_items_grouped(ds, starts_with("cg_adoption_"), sd_gender) # not working 

t.test(ds$sd_gender)
```


```{r include=FALSE}


calculate_conf_intervals <- function(data, cols, alpha = 0.05) {
  # Check parameters
  if (!is.data.frame(data)) {
    stop("Input must be a data frame.")
  }
  
  # Calculate confidence intervals for the mean of each variable
  results <- lapply(cols, function(var) {
    fit <- lm(reformulate(".", response = var), data = data)
    tidy_result <- broom::tidy(fit, conf.int = TRUE) %>%
      dplyr::summarize(
        mean = mean(estimate),
        conf.low = min(conf.low),
        conf.high = max(conf.high)
      ) %>%
      dplyr::mutate(variable = var)
    return(tidy_result)
  })
  
  result <- dplyr::bind_rows(results)
  
  return(result)
}

# Beispiel-Daten
set.seed(123)
data <- data.frame(
  var1 = rnorm(100),
  var2 = rnorm(100),
  var3 = rnorm(100),
  var4 = rnorm(100),
  var5 = rnorm(100)
)

# Konfidenzintervalle berechnen für bestimmte Spalten
cols <- c("var1", "var3", "var5")
result <- calculate_conf_intervals(data, starts_with("var"))

# Ergebnisse anzeigen
print(result)


```


```{r include=FALSE}
x <- stat_counts_one(ds, sd_gender, percent =T)

x <- tab_counts_one(ds, sd_gender, percent =F)

stat_counts_items(ds, starts_with("cg_adoption_"))
stat_metrics_one(ds, sd_age)

For mean: l.model <- lm(mpg ~ 1, mtcars) 

caption=fit$method

fit <- lm(sd_age ~ 1, ds)
result <- broom::tidy(fit, conf.int = TRUE)

# Proportionen für jede Kategorie
prop_table <- prop.table(table(ds$sd_gender))

# Referenzkategorie auswählen (z.B. die erste Kategorie)
reference_category <- names(prop_table)[1]

# Funktion zum Berechnen von Konfidenzintervallen für jede Kategorie
calculate_ci <- function(category_prop, total_obs, alpha) {
  se <- sqrt(category_prop * (1 - category_prop) / total_obs)
  z <- qnorm(1 - alpha / 2)
  margin_error <- z * se
  ci_lower <- category_prop - margin_error
  ci_upper <- category_prop + margin_error
  return(c(ci_lower, ci_upper))
}

# Konfidenzintervalle für jede Kategorie
conf_intervals <- sapply(prop_table, calculate_ci, total_obs = length(ds$sd_gender), alpha = 0.05)


```


```{r include=FALSE}

stat_counts_items(ds, starts_with("cg_adoption_"))
```

```{r}
# Load data 
ds <- volker::chatgpt

# Playground lm 

fit <- stats::lm(sd_age ~ adopter, data = ds)

leveneTest(fit)
shapiro.test(ds$sd_age,ds$adopter)

# Metrics for innovator type items 
tab_metrics_one_grouped(ds, sd_age, adopter)

# Stats table (regression)
# TODO: Fix labels and add another table that shows overall model stats (e.g.R^2)
stat_metrics_one_grouped(ds, sd_age, adopter)

# Plot metrics without stats 
volker::plot_metrics_one_grouped(ds, sd_age, adopter)

# Plot metrics with stats and numbers
plot_metrics_one_grouped(ds, sd_age, adopter, stats = T, numbers = T)
```


```{r}

volker::tab_counts_items(ds, starts_with("adopt"))

# confidence interval for mean 
t.test(ds$sd_age)$conf.int

df <- data.frame(
  ID = 1:6,
  Value1 = c(10, -5, 8, -3, 12,NA),
  Value2 = c(-7, 6, 9, -2, 15,NA), 
  Value3 = c("hallo", "ne", "garnicht", "gehtso", "no", NA)
)

stat_metrics_one_grouped(df, Value1,  Value3, missings = F)
tab_metrics(df, Value)

plot_counts_one_grouped(df, Value3, Value2, missing = T)
plot_counts_items(ds, starts_with("cg_adoption"), missing =T)
plot_metrics_one(df, Value1, negative = T)
stat_metrics_one_grouped(ds, cg_adoption_advantage_01, sd_gender, missings = F)

tab_counts_one(ds, sd_gender)

ds <- volker::chatgpt


result <- ds %>%
    dplyr::count(sd_gender) %>%
    tidyr::drop_na() %>%
    dplyr::mutate("sd_gender" := as.character(sd_gender)) %>% 
    dplyr::mutate(p = n / sum(n)) # %>% 

    # calculate gini
    # TODO: Correct for frequencies?

result <- result %>%  
    dplyr::arrange(n) %>% 
    dplyr::mutate(cumulative_frequencies = cumsum(n),
           cumulative_percentage = cumulative_frequencies / sum(n)) %>%
    summarize(gini = (length(n) + 1 - 
                      2 * sum(cumulative_percentage * n / sum(n))) / 
                      length(n)) 


# Anzahl der Beobachtungen
total_obs <- sum(result$n)

num_groups <- nrow(result)

z_value <- qnorm(1 - (1 - 0.95) / 2)

# Confidence Intervals berechnen
result <- result %>%
  mutate(
    std_error = sqrt(p * (1 - p) / total_obs),
    ci_lower = p - z_value * std_error,
    ci_upper = p + z_value * std_error
  ) 


Gini()

```


```{r}

# Playground 
# perform chi^2 test 

c <- chisq.test(ds$sd_gender, ds$adopter)


z <- cramers_v(c, adjust = F)

tab_metrics_items_cor(ds, starts_with("cg_adoption_adv"))

temp <- tibble(ds$sd_gender, ds$adopter)
temp <- ds %>% 
  group_by(sd_gender) %>% 
  count()

# contingency table 

table(ds$sd_gender, ds$adopter)

temp <- ds %>%
  count(adopter, sd_gender) %>% 
  spread(sd_gender, n, fill = 0) 

temp <- ds %>%
  count(adopter, sd_gender) %>% 
  spread(sd_gender, n) 

temp <- ds %>%
  count(adopter, sd_gender) %>% 
  spread(sd_gender, n, fill = 0) %>%  
  as.data.frame() %>%
  select(-1) %>% 
  chisq.test()

chisq.test(temp)

z <- ds %>%  
  count(sd_gender, adopter)

# Playground 
# plot scatterplot or heatmap 

tab_metrics_items_cor(ds, starts_with("cg_adoption_adv"))

# Scatter

ds %>% 
  ggplot(aes(x = cg_adoption_advantage_04, y = cg_adoption_advantage_02)) +
  geom_point() +
  labs(title = "Scatterplot", x = "X-axis", y = "Y-axis")

# Heatmap

cor <- ds %>% 
  select(cg_adoption_advantage_04,cg_adoption_advantage_02) %>% 
  stats::cor() %>% 
  reshape2::melt()

 cor %>% 
ggplot(aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()
  



```


```{r}

stat_counts_one_grouped(ds, cg_adoption_advantage_01, sd_gender, missings= T)

report_counts(ds, cg_adoption_advantage_01, sd_gender, stats = T)

report_metrics(ds, sd_age, adopter, stats = T)

```


```{r}
