---
title: "Plot variations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Plot variations}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r include=FALSE}

knitr::opts_chunk$set(collapse = TRUE, comment = "#>", echo=TRUE)

library(tidyverse)
library(volker)
theme_set(theme_bw())

data <- volker::chatgpt


# Recode -9 to NA
data <- mutate(data, across(starts_with("cg_adoption_"), ~ na_if(.,-9)  ))

# Add label to sd_alter
data <- set_item_labels(data, tibble("sd_alter","Alter")) 

```

## Frequencies of categorical variables

### 1. One variable: Frequency plot of Gender
```{r results='asis'}

plot_var_counts(data, sd_geschlecht)

```

### 2. Multiple items: Frequency plot for adoption factors
```{r results='asis'}

# Use the .numbers parameter to add counts to the bars
plot_item_counts(data, starts_with("cg_adoption_"), numbers="n")

```

### 3. Two variables: Stacked frequency plot of innovator type by gender

```{r results='asis'}

plot_group_counts(data, in_adoption, sd_geschlecht, prop="rows")

```

## Metric distributions

### Distribution table for one metric variable: Age
```{r results='asis'}

#tab_var_metrics(data, sd_alter)

#plot_var_metrics(data, sd_alter)

```


### Distribution of multiple metric items: Adoption factors
```{r results='asis'}

# Note that negative values are omitted, 
# you can change the behavior with the .negative parameter
plot_item_metrics(data, starts_with("cg_adoption_"))


```

